### PR TITLE
snapclient: Set ALSA_PLUGIN_DIR (109)

### LINKED ISSUE #6307: [BUG] addons snapclient - pulseaudio does not work
### Describe the bug
After installing the snapclient addon, pulseaudio does not work, because the libraries for libasound provided by the addon are not used. libasound does not use LD_LIBRARY_PATH to load additional libraries. Instead it uses ALSA_PLUGIN_DIR, see this [commit](https://github.com/alsa-project/alsa-lib/commit/8580c081c25678d11278efcb61bd15cf44d0a225)

### To Reproduce
1. Install snapclient addon
2. Configure pulseaudio to use a sound card
3. Add asound.conf with a pulseaudio pcm
4. Configure snapclient to use that pcm
5. Observe that snapclient fails to open the pcm when starting

### Informations
 - LE Version: 10.0.0
 - Hardware Platform: RPi4

### PR DESCRIPTION
**Pull request by cr3bs**
Fixes #6307

### CODE REVIEW

File: packages/addons/service/snapclient/source/system.d/service.snapclient.service [hunk 1]
```diff
@@ -4,6 +4,7 @@ After=kodi.service network-online.target sound.target
 Requires=kodi.service network-online.target sound.target
 
 [Service]
+Environment=ALSA_PLUGIN_DIR=/storage/.kodi/addons/service.snapclient/lib/
```
Comment (vpeter4) [inline packages/addons/service/snapclient/source/system.d/service.snapclient.service:7]: Is slash at the end really needed?

Comment (cr3bs) [reply packages/addons/service/snapclient/source/system.d/service.snapclient.service]: @vpeter4 It isn't. Fixed

**Review by CvH — APPROVED** [review]
tx
